services:
  - name: test-nginx
    namespace: rain-container-web
    image: nginx
    version: latest
    replicas: 2
    ports:
      - port: 8080
    envVars:
      - name: Name_Test
        value: Value_test
      - name: NGINX_PORT
        value: 8080