services:
  - name: test-nginx
    namespace: rain-container-web
    image: nginx
    version: latest
    replicas: 2
    hosts:
      - nginx.local
    #TODO  we should be able to set the all ingress settings
    publicPort: 8091
    ports:
      - port: 8091
        targetPort: 80
    envVars:
      - name: Name_Test
        value: Value_test