{{ range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .name }}
  type: ClusterIP
  ports:
  {{ range $index, $port := .ports }}
  - protocol: TCP
    name: port{{ $index }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
  {{ end }}
---
{{ end }}
