{{ range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  type: LoadBalancer
  ports:
  {{ range $index, $port := .ports }}
  - protocol: TCP
    name: port{{ $index }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
  {{ end }}
---
{{ end }}
